### PR TITLE
Add "forceStrings" parameter in mapping configuration

### PR DESCRIPTION
**Pull request by davidrapin**
as requested by @alenegro81 
cc @ikwattro

### CODE REVIEW

**Comment by davidrapin** [comment]
FYI tests are OK on my laptop, I think Travis is just being too slow.

**Comment by ikwattro** [comment]
Thanks! Same here for tests.

**Comment by davidrapin** [comment]
Thanks 👍

**Comment by alenegro81** [comment]
thanks @davidrapin

**Pull request merged**
