### PR TITLE
New Mapping's classes

### PR DESCRIPTION
**Pull request by alenegro81**
The current pull request fixes some issues (8, 11, 12, 14, 15, 20) creating some new Mapping classes and updating old DefaultMapping. In particular:

1. DefaultMapping is changed to support array properties in nodes and relationships. All the available property array types are now supported a part from char and byte that are not created in the right way in the json. 
2. SimpleMapping is created for compatibility, it is the has the same behavior as old DefaultMapping
3. AdvancedMapping use a complete different approach in creating documents. All nodes and relationships are created in the same type (node for nodes, relationship for relationships). Labels are stored as field _labels, while relationship type is stored as _relationship. 

In the AdvancedMapping it is necessary to take care of the properties created on nodes since all of them belong to the same type each property need to have the same value on all the nodes, otherwise it could cause issue in the insertion on the es.

This PR should solve the great part of the current issue on the plugin

---

There is now another mapping possibility like explained in the comments to @johnbodley , the `JsonFileMapping`.

A now working example is : 

```json
{
  "defaults": {
    "key_property": "uuid",
    "nodes_index": "node-index",
    "relationships_index": "relationship-index",
    "include_remaining_properties": true,
    "blacklisted_node_properties": ["password", "uuid"]
  },
  "node_mappings": [
    {
      "condition": "hasLabel('Person')",
      "type": "persons",
      "properties": {
        "name": "getProperty('firstName') + ' ' + getProperty('lastName')",
        "labels": "getLabels()"
      }
    },
    {
      "condition": "hasLabel('Female')",
      "index": "females",
      "type": "girls",
      "properties": {
        "name": "getProperty('firstName')"
      }
    },
    {
      "condition": "getLabels().length == 0",
      "type": "nodes-without-labels"
    },
    {
      "condition": "hasLabel('Node')",
      "type": "nodes"
    }
  ]
}
```

```
{"_index":"females","_type":"girls","_id":"ee42cef0-4ee2-11e6-ad60-5a636a648dcc","_version":1,"found":true,"_source":{"firstName":"Daniela","lastName":"Daniela","name":"Daniela","uuid":"ee42cef0-4ee2-11e6-ad60-5a636a648dcc"}}
{"_index":"node-index","_type":"persons","_id":"ee1640b0-4ee2-11e6-ad60-5a636a648dcc","_version":1,"found":true,"_source":{"firstName":"Michal","lastName":"Bachman","name":"Michal Bachman","uuid":"ee1640b0-4ee2-11e6-ad60-5a636a648dcc","age":30,"labels":["Person","Male"]}}
{"_index":"node-index","_type":"persons","_id":"ee1e5700-4ee2-11e6-ad60-5a636a648dcc","_version":1,"found":true,"_source":{"firstName":"Adam","lastName":"George","name":"Adam George","uuid":"ee1e5700-4ee2-11e6-ad60-5a636a648dcc","labels":["Person","Male"]}}
{"_index":"node-index","_type":"persons","_id":"ee42cef0-4ee2-11e6-ad60-5a636a648dcc","_version":1,"found":true,"_source":{"firstName":"Daniela","lastName":"Daniela","name":"Daniela Daniela","uuid":"ee42cef0-4ee2-11e6-ad60-5a636a648dcc","labels":["Person","Female"]}}
```

It has support for `array` types, nodes without labels, concatenation and more logic available via Spring Expression Language.

Breaking change: the type of the mapping should now be the fully qualified class name of the mapping class.

### CODE REVIEW

**Comment by ikwattro** [comment]
cc @davidrapin

**Comment by ikwattro** [comment]
@davidrapin I added a first version of the doc for the json mapping definition

https://github.com/graphaware/neo4j-to-elasticsearch/blob/features/enhancement_15_20/docs/json-mapper.md

**Comment by ikwattro** [comment]
@davidrapin @johnbodley Merging. Expect the release very soon !

**Comment by johnbodley** [comment]
Awesome. Thanks @ikwattro for all the work. The timing works out perfectly for us as we're hoping to have our Neo4j, ES, and GraphAware system operational in a few days.

**Comment by johnbodley** [comment]
Also @ikwattro what's the typical timeframe with regards to bumping the version of the this package and building a JAR http://products.graphaware.com/?dir=neo4j-to-elasticsearch. In the interim I'm going to build from `master` but the plan moving forward is to move our deployment to Chef and it's easier dealing with versioned software. 

Note on an unrelated note I sense that the tooltips are incorrect for http://products.graphaware.com/?dir=framework-server-community. It states `Compatible with Elasticsearch ...` however I believe this should be `Compatible with Neo4j ...`. This tripped me up previously.

**Comment by ikwattro** [comment]
@johnbodley I can send you a jar if you want one. We plan to release this evening or tomorrow.

**Comment by ikwattro** [comment]
@johnbodley thanks for the tooltip issue

**Comment by johnbodley** [comment]
It can wait. I appreciate the offer.

**Comment by ikwattro** [comment]
@johnbodley would be nice if you could send a brief description of your use case and maybe who is `we`, we love that kind of information and feedback. `christophe@graphaware.com`. 

Thanks !

**Comment by johnbodley** [comment]
@ikwattro email sent.

**Comment by ikwattro** [comment]
@johnbodley @davidrapin 

Releasing now, be patient because it is real PITA process :(

**Comment by ikwattro** [comment]
All went fine, waiting now it is available on maven central.

Already available on our products page btw

http://products.graphaware.com/?dir=neo4j-to-elasticsearch

**Comment by johnbodley** [comment]
Thanks @ikwattro

**Comment by johnbodley** [comment]
@ikwattro is there a typo here? https://github.com/graphaware/neo4j-to-elasticsearch/blob/master/src/main/java/com/graphaware/module/es/mapping/AdvancedMapping.java#L37

The comment mentions that relationships are stored in the `_type` field but the code suggests `_relationship`.

**Comment by davidrapin** [comment]
@johnbodley sorry, that's my mistake while fixing the JavaDoc yesterday in a hurry. I'm fix it in the next release.

**Pull request merged**
