### PR TITLE
Https connectivity

### PR DESCRIPTION
**Pull request by agdelen**

### CODE REVIEW

**Comment by agdelen** [comment]
My fork was behind but i pulled the base fork's master branch and merge with my code, everything seems ok.

**Comment by agdelen** [comment]
Travis has failed to build due to ElasticSearchModuleJsonMappingTest.overallTest but i do not think its related with my code. Please check, if its related to my modifications i will fix as soon as possible.

**Comment by ikwattro** [comment]
@agdelen Thanks. Yes the test suite is a bit greedy for travis, no worries.

**Comment by agdelen** [comment]
Cool, its my pleasure to contribute those beautiful modules. I hope it helps.

**Comment by ikwattro** [comment]
Thanks @agdelen , merged. it will be in next release next week.

**Comment by agdelen** [comment]
Its my pleasure. :)

**Pull request merged**
